---

image: "reporunner/golang-alpine"
checkout_dir: /go/src/github.com/Luzifer/gziphttp

commands:
  - make publish

environment:
  ARCHS: >-
    darwin/amd64
    linux/amd64
    linux/arm
    openbsd/amd64
    openbsd/arm
    plan9/amd64
    plan9/arm
    solaris/amd64
    windows/amd64
  CGO_ENABLED: 0
  GO111MODULE: on
  MOD_MODE: readonly

...
