name: Publish Docker image

on:
  push: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Docker image
        uses: Luzifer/actions/docker-publish@b94e3cd3b956105cbfa85d486921ca809b739af3 # develop
        with:
          image_name: ghcr.io/luzifer/gziphttp
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          registry_user: ${{ github.actor }}
