name: Publish Docker image

on:
  push: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Docker image
        uses: Luzifer/actions/docker-publish@cc7387871607fbf850bdd3cbc6a2683562f829dc # develop
        with:
          image_name: ghcr.io/luzifer/gziphttp
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          registry_user: ${{ github.actor }}
